#!/bin/bash
#
#- Name:                initserver
#- Creation Date:       11-10-2015
#- Author:              jeanmichel cote
#- Github:              https://github.com/jeanmichelcote/scripts/initserver
#- Version:             1.0    
#
#: Usage:               initserver 
#: Description:         Use to set a user directory up with dotfiles on a blank server
#

shopt -s dotglob

now=$(date +%d%m%Y%H%M%S)
localRepo="${HOME}/tmp/test2"
tmp="${localRepo}/tmp"
gitdir="https://github.com/jeanmichelcote/serverutils.git"

# If a temp dir already exist in localRepo, create a subdir within
[[ -d "$tmp" ]] && tmp="${tmp}/${0}.${now}"
mkdir -p "$tmp"
echo "Creating temporary folder"

# Get every hidden file in localRepo, if any, an fill an array with them
read -ra localDotfiles_a <<< \
$( find "$localRepo" ! -path "$localRepo"  -name '.*' -maxdepth 1 | \
  awk '{print}' )

git clone "$gitdir" "$tmp" &>/dev/null 2>&1 && echo "Cloning $gitdir to $tmp"

# Get every directory in remote git repository, if any, and fill an array
read -ra remoteDirs_a <<< \
$( find "$tmp" ! -path "$tmp" -type d -maxdepth 1 | awk '{print}' )

if [[ ${#remoteDirs_a} -eq 0 ]]; then 
  echo "Nothing was downloaded from the server."
  rm -rf "$tmp" && echo "Removing temporary folder"
  exit 1
fi

# Iterate through every remote files and directories 
#+to copy them to local repo and make sure doubles are concatenated
for remdir in "${remoteDirs_a[@]}"; do
  case ${remdir##*/} in
    "scripts"   ) 
                  cp -r "${remdir}" "${localRepo}/bin" 
                  echo "Copying ${remdir} => ${localRepo}/bin" 
                ;;
    ".git"      ) 
                  cp -r "${remdir}" "$localRepo" 
                  echo "Copying ${remdir} => ${localRepo}"       
                ;;
    "dotfiles"  ) 
                  for remfile in "$remdir"/*; do
                    for locfile in "${localDotfiles_a[@]}"; do
                      if [[ "${locfile##*/}" == "${remfile##*/}" ]]; then
                        cat "$remfile" >> "$locfile"
                        echo "Appending $remfile => $locfile"
                      fi
                    done
                    cp "$remfile" "$localRepo"
                    echo "Copying $remfile => $localRepo"
                  done
                ;;
  esac
done
echo "Done iterating through directories"

rm -rf "$tmp"
echo "Removed temporary folder"

# for file in "${localFiles_a[@]}"; do
#   [[ -d $file ]]                && printf "%-10s %s\n" "Directory:" "$file"  && continue
#   [[ ! "${file##*/}" =~ ^\. ]]  && printf "%-10s %s\n" "File:" "$file"       && continue
#   [[ "${file##*/}" =~ ^\. ]]    && printf "%-10s %s\n" "Dotfile:" "$file"    && continue
# done
